apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    deployment: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend
    spec:
      containers:
        - name: canary-frontend
          image: image
          ports:
            - containerPort: 80
