apiVersion: v1
kind: Deployment
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  selector:
    matchLabels:
      run: frontend
    replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - image: ekke020/frontend:1.0
          name: kuber
          ports:
            - containerPort: 80