apiVersion: v1
kind: Service

metadata:
  labels:
    service: frontend-srv
    app: frontend
  name: frontend-srv

spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80