name: Build/Push

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get commit hash
        run: |
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/canary-fronten:${{ env.TAG }}
      - name: Set the image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers.[0].image |= "ekke020/canary-fronten:${{ env.TAG }}"' './kubernetes/canary-fronten-deployment.yaml'
      - name: Push manifest to deployments repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'kubernetes'
          destination-github-username: 'ekke020'
          destination-repository-name: 'canary-deployments'
          user-email: canary-fronten@github.com
          target-branch: main          
          target-directory: raw-configs/canary-fronten
          commit-message: "canary-deployment:${{ env.TAG }}"